---
language: ruby
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.8
    env: PUPPET_GEM_VERSION="~> 3.4"
  - rvm: 2.1.8
    env: PUPPET_GEM_VERSION="~> 3.7"
notifications:
  email: false
